In [2]:
import pandas as pd

### Задание 1
Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:

если источник traffic_source равен yandex или google, то в source_type ставится organic  
для источников paid и email из России - ставим ad  
для источников paid и email не из России - ставим other  
все остальные варианты берем из traffic_source без изменений

In [109]:
visit_log = pd.read_csv(r"C:\Users\user\Desktop\PYDP-19-DSU-4\NumPy, pandas, MPL\10. Pandas\12. Лекция Pandas_Методы_оптимизации\доп_материалы_к_пандас_1_и_2\visit_log.csv", sep = ';')
visit_log['source_type'] = visit_log['traffic_source']
visit_log.loc[(visit_log['region'] == 'Russia') & (visit_log['source_type'].isin(['paid','email'])), 'source_type'] = 'ad'
visit_log.loc[(visit_log['region'] != 'Russia') & (visit_log['source_type'].isin(['paid','email'])), 'source_type'] = 'other'
visit_log.loc[(visit_log['source_type'].isin(['yandex','google'])), 'source_type'] = 'organic'
visit_log

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
...,...,...,...,...,...,...,...
18933,1550094288,57e5ba8560,https://host.ru/c2382eb3d6afc8d0f3,Belarus,98b19810d0,paid,other
18934,1550094296,6f9389ec1b,https://host.ru/f1eb4601740d627ab0,Russia,32ebb20c13,paid,ad
18935,1550094308,e8cf2eb8e6,https://host.ru/a5dda93e70318570c0,Belarus,b85baa8c73,yandex,organic
18936,1550094314,79530b9a67,https://host.ru/6fda01ec57f23abc9e,Russia,e154b06121,paid,ad
18937,1550094323,b3b634f824,https://host.ru/39fa884393666d45fc,Russia,7d27a58fb8,email,ad

### Задание 2

В файле URLs.txt содержатся url страниц новостного сайта. Вам необходимо отфильтровать его по адресам страниц с текстами новостей. Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. Выполните следующие действия:

Прочитайте содержимое файла с датафрейм  
Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии с заданным шаблоном

In [149]:
url_table = pd.read_csv(r"C:\Users\user\Desktop\PYDP-19-DSU-4\NumPy, pandas, MPL\10. Pandas\12. Лекция Pandas_Методы_оптимизации\доп_материалы_к_пандас_1_и_2\URLs.txt")
url_table[url_table['url'].str.contains(r'.*/\d{8}-.*') == True]

                                                  url
3   /politics/36188461-s-marta-zhizn-rossiyan-susc...
4   /world/36007585-tramp-pridumal-kak-reshit-ukra...
5   /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6   /video/36001498-poyavilis-pervye-podrobnosti-g...
7   /world/36007585-tramp-pridumal-kak-reshit-ukra...
..                                                ...
88  /cis/35984145-kreml-prokommentiroval-soobschen...
89  /video/36071019-olimpiyskie-obekty-rio-prevrat...
90  /science/36151301-nazvano-posledstvie-zloupotr...
91  /incidents/36027330-vospitatelnitsu-zatravili-...
92  /world/36103095-dominikanskih-zhurnalistov-ubi...

[84 rows x 1 columns]

### Задание 3

Используйте файл с оценками фильмов ml-latest-small/ratings.csv. Посчитайте среднее время жизни пользователей, которые выставили более 100 оценок. Под временем жизни понимается разница между максимальным и минимальным значением столбца timestamp для данного значения userId.

In [8]:
ratings = pd.read_csv(r"C:\Users\user\Desktop\PYDP-19-DSU-4\NumPy, pandas, MPL\10. Pandas\12. Лекция Pandas_Методы_оптимизации\доп_материалы_к_пандас_1_и_2\ml-latest-small\ratings.csv")
users = ratings.pivot_table(index = 'userId', values = 'timestamp', aggfunc = ['min','max','count'])
users['time_life'] = (users['max']['timestamp'] - users['min']['timestamp'])/users['count']['timestamp']
users[users['count']['timestamp']>100].sort_values(by = 'time_life', ascending=False).reset_index()

    userId         min         max     count     time_life
             timestamp   timestamp timestamp
0      427   939332587  1415901843       294  1.620984e+06
1      219   974474429  1156789022       138  1.321120e+06
2      648  1138477436  1460757570       256  1.258907e+06
3       68  1194740954  1346824858       123  1.236455e+06
4      257  1338006929  1449941803       103  1.086746e+06
..     ...         ...         ...       ...           ...
253    647   947292184   947293361       150  7.846667e+00
254    433  1417929781  1417931291       198  7.626263e+00
255    316  1460822646  1460823562       140  6.542857e+00
256    609  1029869519  1029870367       140  6.057143e+00
257    536   829471719   829471925       109  1.889908e+00

[258 rows x 5 columns]

### Задание 4

Дана статистика услуг перевозок клиентов компании по типам (см. файл “Python_13_join.ipynb” в разделе Материалы для лекции «Продвинутый pandas» ---- Ноутбуки к лекции «Продвинутый pandas»).  
Необходимо сформировать две таблицы:  
таблицу с тремя типами выручки для каждого client_id без указания адреса клиента  
аналогичную таблицу по типам выручки с указанием адреса клиента

In [181]:
rzd = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115],
        'rzd_revenue': [1093, 2810, 10283, 5774, 981]
    }
)

In [180]:
auto = pd.DataFrame(
    {
        'client_id': [113, 114, 115, 116, 117],
        'auto_revenue': [57483, 83, 912, 4834, 98]
    }
)

In [199]:
air = pd.DataFrame(
    {
        'client_id': [115, 116, 117, 118],
        'air_revenue': [81, 4, 13, 173]
    }
)

In [200]:
client_base = pd.DataFrame(
    {
        'client_id': [111, 112, 113, 114, 115, 116, 117, 118],
        'address': ['Комсомольская 4', 'Энтузиастов 8а', 'Левобережная 1а', 'Мира 14', 'ЗЖБИиДК 1', 
                    'Строителей 18', 'Панфиловская 33', 'Мастеркова 4']
    }
)

In [211]:
#1. таблица с тремя типами выручки для каждого client_id без указания адреса клиента:

print((client_base.merge(rzd, how = 'left', on = 'client_id').
 merge(auto, how = 'left', on = 'client_id').
 merge(air, how = 'left', on = 'client_id').
 drop(['address'], axis = 1).
 fillna(0).), "\n","\n")

#2. аналогичную таблицу по типам выручки с указанием адреса клиента

print(client_base.merge(rzd, how = 'left', on = 'client_id').
 merge(auto, how = 'left', on = 'client_id').
 merge(air, how = 'left', on = 'client_id').
 fillna(0))

   client_id  rzd_revenue  auto_revenue  air_revenue
0        111       1093.0           0.0          0.0
1        112       2810.0           0.0          0.0
2        113      10283.0       57483.0          0.0
3        114       5774.0          83.0          0.0
4        115        981.0         912.0         81.0
5        116          0.0        4834.0          4.0
6        117          0.0          98.0         13.0
7        118          0.0           0.0        173.0


   client_id          address  rzd_revenue  auto_revenue  air_revenue
0        111  Комсомольская 4       1093.0           0.0          0.0
1        112   Энтузиастов 8а       2810.0           0.0          0.0
2        113  Левобережная 1а      10283.0       57483.0          0.0
3        114          Мира 14       5774.0          83.0          0.0
4        115        ЗЖБИиДК 1        981.0         912.0         81.0
5        116    Строителей 18          0.0        4834.0          4.0
6        117  Панфиловская 33          0.0          98.0         13.0
7        118     Мастеркова 4          0.0           0.0        173.0