## Обязательная часть

Будем осуществлять работу с непростым [набором данных](https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.csv) о состоянии здоровья лошадей, испытывающих кишечные колики. 

### Задание 1. Базовое изучение

Изучить представленный набор данных на основе [описания его столбцов](https://raw.githubusercontent.com/obulygin/pyda_homeworks/master/statistics_basics/horse_data.names) и выбрать 8 столбцов для дальнейшего изучения (среди них должны быть как числовые, так и категориальные). Провести расчет базовых метрик для них, кратко описать результаты.

### Задание 2. Работа с выбросами

В выбранных числовых столбцах найти выбросы, выдвинуть гипотезы об их причинах и проинтерпретировать результаты. Принять и обосновать решение о дальнейшей работе с ними.

### Задание 3. Работа с пропусками

Рассчитать количество выбросов для всех выбранных столбцов. Принять и обосновать решение о методе работы с пропусками по каждому столбцу, сформировать датафрейм, в котором пропуски будут отсутствовать.

In [1]:
import pandas as pd

In [353]:
df = pd.read_csv('C:/Users/user/Desktop/PYDP-19-DSU-4/NumPy, pandas, MPL/11.MPL/Вебинар от 02.07.2021/практика_и_дз/horse_data.csv', names = ['surg', 'age', 'Hosp_Num', 'rectal_temp', 'pulse', 'respiratory_rate', 'temp_of_extrem', 'perip_pulse', 'mucous_membranes', 'cap_ref_time', 'pain', 'peristalsis', 'abdom_distension', 'nasogastric_tube', 'nasogastr_refl', 'nasogastr_refl_PH', 'rectal_exam_feces', 'abdomen', 'pack_cell_vol', 'total_protein', 'abdom_appearance', 'abdom_total_protein', 'outcome', 'surgical_lesion', '25', '26', '27', 'cp_data'], sep = ',')
for i in df:
    df[i] = df[i].apply(pd.to_numeric, errors= 'coerce')
df.info()
df.describe()
#(df.isna().mean() * 100).round(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   surg                 299 non-null    float64
 1   age                  300 non-null    int64
 2   Hosp_Num             300 non-null    int64
 3   rectal_temp          240 non-null    float64
 4   pulse                276 non-null    float64
 5   respiratory_rate     242 non-null    float64
 6   temp_of_extrem       244 non-null    float64
 7   perip_pulse          231 non-null    float64
 8   mucous_membranes     253 non-null    float64
 9   cap_ref_time         268 non-null    float64
 10  pain                 245 non-null    float64
 11  peristalsis          256 non-null    float64
 12  abdom_distension     244 non-null    float64
 13  nasogastric_tube     196 non-null    float64
 14  nasogastr_refl       194 non-null    float64
 15  nasogastr_refl_PH    53 non-null     float64
 16  rectal_exam_feces    198 non-null    float64
 17  abdomen              182 non-null    float64
 18  pack_cell_vol        271 non-null    float64
 19  total_protein        267 non-null    float64
 20  abdom_appearance     135 non-null    float64
 21  abdom_total_protein  102 non-null    float64
 22  outcome              299 non-null    float64
 23  surgical_lesion      300 non-null    int64
 24  25                   300 non-null    int64
 25  26                   300 non-null    int64
 26  27                   300 non-null    int64
 27  cp_data              300 non-null    int64
dtypes: float64(21), int64(7)
memory usage: 65.8 KB

surg                    0.33
age                     0.00
Hosp_Num                0.00
rectal_temp            20.00
pulse                   8.00
respiratory_rate       19.33
temp_of_extrem         18.67
perip_pulse            23.00
mucous_membranes       15.67
cap_ref_time           10.67
pain                   18.33
peristalsis            14.67
abdom_distension       18.67
nasogastric_tube       34.67
nasogastr_refl         35.33
nasogastr_refl_PH      82.33
rectal_exam_feces      34.00
abdomen                39.33
pack_cell_vol           9.67
total_protein          11.00
abdom_appearance       55.00
abdom_total_protein    66.00
outcome                 0.33
surgical_lesion         0.00
25                      0.00
26                      0.00
27                      0.00
cp_data                 0.00
dtype: float64

In [393]:
df = pd.read_csv('C:/Users/user/Desktop/PYDP-19-DSU-4/NumPy, pandas, MPL/11.MPL/Вебинар от 02.07.2021/практика_и_дз/horse_data.csv', names = ['surg', 'age', 'Hosp_Num', 'rectal_temp', 'pulse', 'respiratory_rate', 'temp_of_extrem', 'perip_pulse', 'mucous_membranes', 'cap_ref_time', 'pain', 'peristalsis', 'abdom_distension', 'nasogastric_tube', 'nasogastr_refl', 'nasogastr_refl_PH', 'rectal_exam_feces', 'abdomen', 'pack_cell_vol', 'total_protein', 'abdom_appearance', 'abdom_total_protein', 'outcome', 'surgical_lesion', '25', '26', '27', 'cp_data'], sep = ',')
for i in df:
    df[i] = df[i].apply(pd.to_numeric, errors= 'coerce')
print('Описательная статистика по изучению лошадиных колик. Общая информация.')
print('В изучении лошадиных колик участвовало ', len(df['Hosp_Num'].unique()),' лошадей. По некоторым из них было несколько случаев болезни.')
print('При этом было рассмотрено всего - ', len(df), ' историй болезни:')
print()
print(round((len(df[df['age'] == 1])/len(df))*100, 2), '% - ', len(df[df['age'] == 1]), 'истории болезни взрослых', len(df[df['age'] == 1]['Hosp_Num'].unique()) ,'лошадей')
print(round((len(df[df['age'] == 9])/len(df))*100, 2), '% - ', len(df[df['age'] == 9]), 'истории болезни молодых', len(df[df['age'] == 9]['Hosp_Num'].unique()) ,'лошадей возраста <6 месяцев')
print()
print('Из них:')

print(round((len(df[df['surgical_lesion'] == 1])/len(df))*100, 2), '% - ', len(df[df['surgical_lesion'] == 1]), 'случаев болезни были хирургическими, из которых ', len(df[df['surgical_lesion'] == 1]['Hosp_Num'].unique()), 'случаев были первично и ', len(df[df['surgical_lesion'] == 1]) - len(df[df['surgical_lesion'] == 1]['Hosp_Num'].unique()), ' случаев было повторно' )
print(round((len(df[df['surgical_lesion'] == 2])/len(df))*100, 2), '% - ', len(df[df['surgical_lesion'] == 2]), 'случаев болезни не были хирургическими, из которых ', len(df[df['surgical_lesion'] == 2]['Hosp_Num'].unique()), 'случаев были первично и ', len(df[df['surgical_lesion'] == 2]) - len(df[df['surgical_lesion'] == 2]['Hosp_Num'].unique()), ' случаев было повторно')
print()
print('При этом: ')

print('Из общей статистики по заполненности полей с показателями видно, что показатель отображающий факт хирургического вмешательства "surg" не заполнен у 1 случая болезни')
#df[df['surg'].fillna(0) == 0]) #здесь можно посмотреть всю ту строку, где не заполнен показатель surg
print('При этом у этой строки известен показатель "surgical_lesion", который отображает, относится ли случай в целом к хирургическому или нет')
print()
print(df[df['surg'].fillna(0) == 0][['surg', 'age', 'Hosp_Num', 'surgical_lesion']])
print()
print('С учетом того, что случай относится к хирургическому и что в большей степени отнесение случая к хирургическому совпадало с фактом проведения операции в итоге, то проставим ему параметр "surg" = 1, что означает. что хирургическое вмешательство было по факту')
df['surg'].fillna(1, inplace = True)
print()

print(round((len(df[df['surg'] == 1])/len(df))*100, 2), '% - ', len(df[df['surg'] == 1]), 'случаев, где лошадям сделали операцию, из которых ', len(df[df['surg'] == 1]['Hosp_Num'].unique()), 'случаев были первично и ', len(df[df['surg'] == 1]) - len(df[df['surg'] == 1]['Hosp_Num'].unique()), ' случаев было повторно' )
print(round((len(df[df['surg'] == 2])/len(df))*100, 2), '% - ', len(df[df['surg'] == 2]), 'случаев, где лошадей лечили без хирургического вмешательства, из которых ', len(df[df['surg'] == 2]['Hosp_Num'].unique()), 'случаев были первично и ', len(df[df['surg'] == 2]) - len(df[df['surg'] == 2]['Hosp_Num'].unique()), ' случаев было повторно')
print()

print('Статистика по результатам окончания лечения:')
print('По одному из случаев болезни не проставлен показатель результатов лечения. Чтобы его проставить необходимо проанализировать другие параметры лошади, и в том числе код типа поражения(пп. 25). В данном случае, код типа поражения 3111, что означает закупорка тонкой кишки. Показатели ректальной пульса и эритроцитов в крови в норме, показатель рекатльной температуры не сильно высокий. Как правило такие случаи лечатся и хирургическим путем и даже без вмешательства и исход в большей степени у данного кода - положительный')
print('С учетом вышесказанного показатель "outcome" будет заполнен значением 1 - случай закончился благополучно')
df['outcome'].fillna(1, inplace = True)
print()
print(round((len(df[df['outcome'] == 2])/len(df))*100, 2), '% - ', len(df[df['outcome'] == 2]), 'случаев закончились смертью')
print(round((len(df[df['outcome'] == 3])/len(df))*100, 2), '% - ', len(df[df['outcome'] == 3]), 'случаев закончились эвтаназией')
print(round((len(df[df['outcome'] == 1])/len(df))*100, 2), '% - ', len(df[df['outcome'] == 1]), 'случаев закончились благополучно')

Описательная статистика по изучению лошадиных колик. Общая информация.
В изучении лошадиных колик участвовало  284  лошадей. По некоторым из них было несколько случаев болезни.
При этом было рассмотрено всего -  300  историй болезни:

92.0 % -  276 истории болезни взрослых 260 лошадей
8.0 % -  24 истории болезни молодых 24 лошадей возраста <6 месяцев

Из них:
63.67 % -  191 случаев болезни были хирургическими, из которых  182 случаев были первично и  9  случаев было повторно
36.33 % -  109 случаев болезни не были хирургическими, из которых  104 случаев были первично и  5  случаев было повторно

При этом:
Из общей статистики по заполненности полей с показателями видно, что показатель отображающий факт хирургического вмешательства "surg" не заполнен у 1 случая болезни
При этом у этой строки известен показатель "surgical_lesion", который отображает, относится ли случай в целом к хирургическому или нет

     surg  age  Hosp_Num  surgical_lesion
132   NaN    1    534572                1

С учетом того, что случай относится к хирургическому и что в большей степени отнесение случая к хирургическому совпадало с фактом проведения операции в итоге, то проставим ему параметр "surg" = 1, что означает. что хирургическое вмешательство было по факту

60.33 % -  181 случаев, где лошадям сделали операцию, из которых  172 случаев были первично и  9  случаев было повторно
39.67 % -  119 случаев, где лошадей лечили без хирургического вмешательства, из которых  113 случаев были первично и  6  случаев было повторно

Статистика по результатам окончания лечения:
По одному из случаев болезни не проставлен показатель результатов лечения. Чтобы его проставить необходимо проанализировать другие параметры лошади, и в том числе код типа поражения(пп. 25). В данном случае, код типа поражения 3111, что означает закупорка тонкой кишки. Показатели ректальной пульса и эритроцитов в крови в норме, показатель рекатльной температуры не сильно высокий. Как правило такие случаи лечатся и хирургическим путем и даже без вмешательства и исход в большей степени у данного кода - положительный
С учетом вышесказанного показатель "outcome" будет заполнен значением 1 - случай закончился благополучно

25.67 % -  77 случаев закончились смертью
14.67 % -  44 случаев закончились эвтаназией
59.67 % -  179 случаев закончились благополучно

In [379]:
print('Статистика по температуре: ')
print('--------------------------------------------------------------------------------------')
print('Cредняя ректальная температура лошади составляет ', round(df.rectal_temp.mean(),3), '. Отклонение от нормы: ', round((df.rectal_temp.mean() - 37.8), 3))
print('Медиана по значениям температуры - ', df.rectal_temp.median(), '. Отклонение от нормы: ', round((df.rectal_temp.median() - 37.8), 3))
print('Температура наиболее часто повторяющаяся - ', df.rectal_temp.mode()[0], '. Она наблюдалась в ', round(len(df.rectal_temp[df.rectal_temp == df.rectal_temp.mode()[0]])/len(df.rectal_temp)*100, 2), ' % случаев.')
print('Максимальное значение температуры - ', df.rectal_temp.max())
print('Минимальное значение температуры - ', df.rectal_temp.min())
print('Размах измеренных температур: ', round(df.rectal_temp.max() - df.rectal_temp.min(), 2))
print('СКО - ', df.rectal_temp.std())
print('Дисперсия - ', df.rectal_temp.var())
q1 = df.rectal_temp.quantile(0.25)
q3 = df.rectal_temp.quantile(0.75)
iqr = q3 - q1
lb = q1 - (1.5 * iqr) 
ub = q3 + (1.5 * iqr)
df2_outliers = df[df.rectal_temp.between(lb, ub, inclusive=True)]
print('Q1 - ', q1, '; Q3 - ', q3, '; IQR: ', round(iqr, 2))
df2_outliers
df3 = pd.concat([df, df2_outliers]).drop_duplicates(keep=False).sort_values('rectal_temp')
df3['rectal_temp'] = df3['rectal_temp'].fillna(0)
print('Кол-во выбросов из основного скопления данных по темп составило: ', len(df3), ', из которых по причине того, что температура не была указана - ', len(df3) - len(df3[df3.rectal_temp != 0]), '. Т.к. медиана, среднее значение и мода практически совпадают, а Q3 и Q1 также не далеки от них, то все пропуски можно заполнить значением Моды.')
print( 'Кол-во актуальных выбросов из основного скопления данных по темп составило:', len(df3[df3.rectal_temp != 0]), '. Они несут допустимые значения и их можно учитывать в рассчетах.')
print('Выбросы без неуказанных значений:')
df3[df3.rectal_temp != 0]

Статистика по температуре:
--------------------------------------------------------------------------------------
Cредняя ректальная температура лошади составляет  38.168 . Отклонение от нормы:  0.368
Медиана по значениям температуры -  38.2 . Отклонение от нормы:  0.4
Температура наиболее часто повторяющаяся -  38.0 . Она наблюдалась в  8.67  % случаев.
Максимальное значение температуры -  40.8
Минимальное значение температуры -  35.4
Размах измеренных температур:  5.4
СКО -  0.7322886641121578
Дисперсия -  0.5362466875871686
Q1 -  37.8 ; Q3 -  38.5 ; IQR:  0.7
Кол-во выбросов из основного скопления данных по темп составило:  74 , из которых по причине того, что температура не была указана -  60 . Т.к. медиана, среднее значение и мода практически совпадают, а Q3 и Q1 также не далеки от них, то все пропуски можно заполнить значением Моды.
Кол-во актуальных выбросов из основного скопления данных по темп составило: 14 . Они несут допустимые значения и их можно учитывать в рассчетах.
Выбросы без неуказанных значений:

,surg,age,Hosp_Num,rectal_temp,pulse,respiratory_rate,temp_of_extrem,perip_pulse,mucous_membranes,cap_ref_time,...,pack_cell_vol,total_protein,abdom_appearance,abdom_total_protein,outcome,surgical_lesion,25,26,27,cp_data
44,1.0,1,535407,35.4,140.0,24.0,3.0,3.0,4.0,2.0,...,57.0,69.0,3.0,2.0,3.0,1,3205,0,0,2
141,2.0,1,522979,36.0,42.0,30.0,NaN,NaN,5.0,1.0,...,64.0,6.8,NaN,NaN,2.0,2,1400,0,0,2
238,2.0,1,528702,36.1,88.0,NaN,3.0,3.0,3.0,1.0,...,45.0,7.0,3.0,4.8,3.0,1,2209,0,0,1
80,1.0,1,527518,36.4,98.0,35.0,3.0,3.0,4.0,1.0,...,47.0,6.4,3.0,3.6,2.0,1,2205,0,0,1
118,1.0,1,533983,36.5,78.0,30.0,1.0,NaN,1.0,1.0,...,34.0,75.0,2.0,1.0,1.0,1,3112,6112,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.0,3.4,1.0,1,2208,0,0,1
251,2.0,1,527940,36.6,42.0,18.0,3.0,3.0,2.0,1.0,...,52.0,7.1,NaN,NaN,2.0,1,5111,0,0,2
99,2.0,1,530002,39.6,108.0,51.0,3.0,3.0,6.0,2.0,...,59.0,8.0,2.0,2.6,1.0,2,4300,0,0,1
75,1.0,9,534092,39.7,100.0,NaN,3.0,3.0,5.0,2.0,...,48.0,57.0,2.0,2.0,3.0,1,1400,0,0,2
20,1.0,1,530157,39.9,72.0,60.0,1.0,1.0,5.0,2.0,...,46.0,6.1,2.0,NaN,1.0,1,2111,0,0,2
281,2.0,1,530624,40.0,78.0,NaN,3.0,3.0,5.0,1.0,...,66.0,6.5,NaN,NaN,2.0,1,8400,0,0,1
54,2.0,1,529461,40.3,114.0,36.0,3.0,3.0,1.0,2.0,...,57.0,8.1,3.0,4.5,3.0,1,7400,0,0,1
91,2.0,1,529461,40.3,114.0,36.0,3.0,3.0,1.0,2.0,...,57.0,8.1,3.0,4.5,2.0,1,3205,0,0,1
259,1.0,1,527734,40.8,72.0,42.0,3.0,3.0,1.0,1.0,...,54.0,7.4,3.0,NaN,2.0,1,11400,0,0,1

In [380]:
print('Статистика по пульсу: ')
print('--------------------------------------------------------------------------------------')
print('Cредний пульс лошади составляет ', round(df.pulse.mean()), '. Отклонение от верхнего предела нормы: ', (round(df.pulse.mean()) - 40))
print('Медиана по значениям пульса - ', df.pulse.median(), '. Отклонение от верхнего предела нормы: ', df.pulse.median() - 40)
print('Пульс наиболее часто повторяющийся - ', df.pulse.mode()[0], '. Он наблюдался в ', round(len(df.pulse[df.pulse == df.pulse.mode()[0]])/len(df.pulse)*100, 2), ' % случаев.')
print('Максимальное значение пульса - ', df.pulse.max())
print('Минимальное значение пульса - ', df.pulse.min())
print('Размах значений пульса: ', round(df.pulse.max() - df.pulse.min(), 2))
print('СКО - ', df.pulse.std())
print('Дисперсия - ', df.pulse.var())
q1 = df.pulse.quantile(0.25)
q3 = df.pulse.quantile(0.75)
iqr = q3 - q1
lb = q1 - (1.5 * iqr) 
ub = q3 + (1.5 * iqr)
df2_outliers = df[df.pulse.between(lb, ub, inclusive=True)]
print('Q1 - ', q1, '; Q3 - ', q3, '; IQR: ', round(iqr, 2))
df3 = pd.concat([df, df2_outliers]).drop_duplicates(keep=False).sort_values('pulse')
df3['pulse'] = df3['pulse'].fillna(0)
print('Кол-во выбросов из основного скопления данных по пульсу составило - ', len(df3), ', из которых по причине того, что пульс не был указан - ', len(df3) - len(df3[df3.pulse != 0]), '. Оставшиеся выбросы несут допустимые значения и их можно учитывать в рассчетах.')
print('Кол-во актуальных выбросов из основного скопления данных по пульсу составило:', len(df3[df3.pulse != 0]))
print('Можно было бы проследить динамику значения пульса (примерно) в зависимости от температуры лошади, а также от показателя силы боли, например. Но если идти наиболее упрощенным путем, то с учетом того, что наибольшая часть лошадей (3/4 точно) имеет повышенный пульс, то я бы заполнила пустые значения средним значением или значением медианы. И т.к. оба значения повышенные, то по сути это не будет играть принципиальную роль.')
print('Среднее значение, значение медианы, и даже значение Q1 говорит о том, что практически у всех лошадей пульс сильно выше максимальной нормы (30-40 ударов в минуту), что говорит о болезненном поражении и/или шоке')
print('Выбросы без неуказанных значений:')
df3[df3.pulse != 0]

Статистика по пульсу:
--------------------------------------------------------------------------------------
Cредний пульс лошади составляет  72 . Отклонение от верхнего предела нормы:  32
Медиана по значениям пульса -  64.0 . Отклонение от верхнего предела нормы:  24.0
Пульс наиболее часто повторяющийся -  48.0 . Он наблюдался в  9.33  % случаев.
Максимальное значение пульса -  184.0
Минимальное значение пульса -  30.0
Размах значений пульса:  154.0
СКО -  28.630556660735003
Дисперсия -  819.7087747035575
Q1 -  48.0 ; Q3 -  88.0 ; IQR:  40.0
Кол-во выбросов из основного скопления данных по пульсу составило -  29 , из которых по причине того, что пульс не был указан -  24 . Оставшиеся выбросы несут допустимые значения и их можно учитывать в рассчетах.
Кол-во актуальных выбросов из основного скопления данных по пульсу составило: 5
Можно было бы проследить динамику значения пульса (примерно) от температуры лошади, а также от показатели силы боли, например. Но если идти наиболее упрощенным путем, то с учетом того, что наибольшая часть лошадей (3/4 точно) имеет повышенный пульс, то я бы заполнила пустые значения средним значением или значением медианы. И т.к. оба значения повышенные, то по сути это не будет играть принципиальную роль.
Среднее значение, значение медианы, и даже значение Q1 говорит о том, что практически у всех лошадей пульс сильно выше максимальной нормы (30-40 ударов в минуту), что говорит о болезненном поражении и/или шоке
Выбросы без неуказанных значений:

,surg,age,Hosp_Num,rectal_temp,pulse,respiratory_rate,temp_of_extrem,perip_pulse,mucous_membranes,cap_ref_time,...,pack_cell_vol,total_protein,abdom_appearance,abdom_total_protein,outcome,surgical_lesion,25,26,27,cp_data
41,2.0,9,5288249,39.0,150.0,72.0,NaN,NaN,NaN,NaN,...,47.0,8.5,NaN,0.1,1.0,1,9400,0,0,1
275,1.0,9,5297159,38.8,150.0,50.0,1.0,3.0,6.0,2.0,...,50.0,6.2,NaN,NaN,2.0,1,4207,0,0,2
55,1.0,9,5282839,38.6,160.0,20.0,3.0,NaN,5.0,1.0,...,38.0,NaN,2.0,NaN,2.0,1,7111,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
255,1.0,9,5294539,38.8,184.0,84.0,1.0,NaN,1.0,1.0,...,33.0,3.3,NaN,NaN,2.0,1,7111,0,0,2

In [375]:
print('Статистика по кол-ву эритроцитов в крови: ')
print('--------------------------------------------------------------------------------------')
print('Cреднее кол-во эритроцитов в крови - ', round(df.pack_cell_vol.mean()), '. Отклонение от верхнего предела нормы: ', (round(df.pack_cell_vol.mean()) - 50), '- в пределах нормы.')
print('Медиана по значениям эритроцитов в крови - ', df.pack_cell_vol.median(), '. Отклонение от верхнего предела нормы: ', df.pack_cell_vol.median() - 50, '- в пределах нормы.')
print('Мода эритроцитов в крови - ', df.pack_cell_vol.mode()[0], ' - в пределах нормы (от 30 до 50). Она наблюдалась в ', round(len(df.pack_cell_vol[df.pack_cell_vol == df.pack_cell_vol.mode()[0]])/len(df.pack_cell_vol)*100, 2), ' % случаев.')
print('Максимальное значение - ', df.pack_cell_vol.max())
print('Минимальное значение - ', df.pack_cell_vol.min())
print('Размах значений: ', round(df.pack_cell_vol.max() - df.pack_cell_vol.min(), 2))
print('СКО - ', df.pack_cell_vol.std())
print('Дисперсия - ', df.pack_cell_vol.var())
q1 = df.pack_cell_vol.quantile(0.25)
q3 = df.pack_cell_vol.quantile(0.75)
iqr = q3 - q1
lb = q1 - (1.5 * iqr) 
ub = q3 + (1.5 * iqr)
df2_outliers = df[df.pack_cell_vol.between(lb, ub, inclusive=True)]
print('Q1 - ', q1, '; Q3 - ', q3, '; IQR: ', round(iqr, 2))
df3 = pd.concat([df, df2_outliers]).drop_duplicates(keep=False).sort_values('pack_cell_vol')
df3['pack_cell_vol'] = df3['pack_cell_vol'].fillna(0)
print('Кол-во выбросов из основного скопления данных по эритроцитам в крови составило - ', len(df3), ', из которых по причине того, что данные не были указаны - ', len(df3) - len(df3[df3.pack_cell_vol != 0]), '. Оставшиеся выбросы несут допустимые значения и их можно учитывать в рассчетах.')
print('С учетом того, что у большей части лошадей кол-во эритроцитов в крови не выходило выше верхнего предела нормы (50), а среднее значение и значение медианы практически совпадают - 46 и 45, то все отсутствующие данные я был заполнила показателем медианы.')
print( 'Кол-во актуальных выбросов из основного скопления данных по эритроцитам в крови составило:', len(df3[df3.pack_cell_vol != 0]))
print('Среднее значение, значение медианы, и значения по квантилям говорят о том, что около у 1/4 лошадей кол-во эритроцитов было выше верхнего уровня нормы, а у остальных примерно в пределах нормы (от 30 до 50).')
print('Выбросы без неуказанных значений:')
df3[df3.pack_cell_vol != 0]

Статистика по кол-ву эритроцитов в крови:
--------------------------------------------------------------------------------------
Cреднее кол-во эритроцитов в крови -  46 . Отклонение от верхнего предела нормы:  -4 - в пределах нормы.
Медиана по значениям эритроцитов в крови -  45.0 . Отклонение от верхнего предела нормы:  -5.0 - в пределах нормы.
Мода эритроцитов в крови -  37.0  - в пределах нормы (от 30 до 50). Она наблюдалась в  5.33  % случаев.
Максимальное значение -  75.0
Минимальное значение -  23.0
Размах значений:  52.0
СКО -  10.419334549704114
Дисперсия -  108.56253245865784
Q1 -  38.0 ; Q3 -  52.0 ; IQR:  14.0
Кол-во выбросов из основного скопления данных по эритроцитам в крови составило -  32 , из которых по причине того, что данные не были указаны -  29 . Оставшиеся выбросы несут допустимые значения и их можно учитывать в рассчетах.
Кол-во актуальных выбросов из основного скопления данных по эритроцитам в крови составило: 3
Среднее значение, значение медианы, и значения по квантилям говорят о том, что около у 1/4 лошадей кол-во эритроцитов было выше верхнего уровня нормы, а у остальных примерно в пределах нормы (от 30 до 50).
Выбросы без неуказанных значений:

,surg,age,Hosp_Num,rectal_temp,pulse,respiratory_rate,temp_of_extrem,perip_pulse,mucous_membranes,cap_ref_time,...,pack_cell_vol,total_protein,abdom_appearance,abdom_total_protein,outcome,surgical_lesion,25,26,27,cp_data
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
144,1.0,1,534519,37.1,84.0,40.0,3.0,3.0,6.0,1.0,...,75.0,81.0,NaN,NaN,3.0,2,1400,0,0,2
151,1.0,1,529399,39.3,NaN,NaN,4.0,3.0,6.0,2.0,...,75.0,NaN,3.0,4.3,2.0,1,2207,0,0,1

In [397]:
print('Статистика по анализу кол-ва белка: ')
print('--------------------------------------------------------------------------------------')
print('Cреднее кол-во белка - ', round(df.total_protein.mean()), '. Отклонение от верхнего предела нормы: ', (round(df.total_protein.mean()) - 7.5))
print('Медиана по белку - ', df.total_protein.median(), '. Отклонение от верхнего предела нормы: ', df.total_protein.median() - 7.5, '- в пределах нормы.')
print('Мода по белку - ', df.total_protein.mode()[0], ' - в пределах нормы (от 6 до 7.5). Она наблюдалась в ', round(len(df.total_protein[df.total_protein == df.total_protein.mode()[0]])/len(df.total_protein)*100, 2), ' % случаев.')
print('Максимальное значение - ', df.total_protein.max())
print('Минимальное значение - ', df.total_protein.min())
print('Размах значений: ', round(df.total_protein.max() - df.total_protein.min(), 2))
print('СКО - ', df.total_protein.std())
print('Дисперсия - ', df.total_protein.var())
q1 = df.total_protein.quantile(0.25)
q3 = df.total_protein.quantile(0.75)
iqr = q3 - q1
lb = q1 - (1.5 * iqr) 
ub = q3 + (1.5 * iqr)
df2_outliers = df[df.total_protein.between(lb, ub, inclusive=True)]
print('Q1 - ', q1, '; Q3 - ', q3, '; IQR: ', round(iqr, 2))
df3 = pd.concat([df, df2_outliers]).drop_duplicates(keep=False).sort_values('total_protein')
df3['total_protein'] = df3['total_protein'].fillna(0)
print('Кол-во выбросов из основного скопления данных по белку составило - ', len(df3), ', из которых по причине того, что данные не были указаны - ', len(df3) - len(df3[df3.total_protein != 0]))
print('По анализам белка ситуация не совсем стандартная. половина показателей по белку ниже или равна верхнему пределу нормы, а другая половина сильно завышена. И поэтому среднее значение по показателю белка сильно отличается и от медианы и от моды. В данном случае необходимо или не учитывать 33 строки с незанесенными данными, или исследовать более подробно зависимости показателя белка от других параметров и только после этого проставлять какое либо значение.')
print( 'Кол-во актуальных выбросов из основного скопления данных по белку составило:', len(df3[df3.total_protein != 0]))
print('Значение медианы, и значение по первому квантилю говорят о том, что около у 1/2 лошадей кол-во белка было в пределах номры (от 6 до 7.5). И примерно у второй половины лошадей кол-во белка сильно завышено, и именно поэтому случаи с превышением белка в 10 раз выше верхнего предела нормы не попали в выбросы.')
print('Выбросы без неуказанных значений:')
df3[df3.total_protein == 0].head()

Статистика по анализу кол-ва белка:
--------------------------------------------------------------------------------------
Cреднее кол-во белка -  24 . Отклонение от верхнего предела нормы:  16.5
Медиана по белку -  7.5 . Отклонение от верхнего предела нормы:  0.0 - в пределах нормы.
Мода по белку -  6.5  - в пределах нормы (от 6 до 7.5). Она наблюдалась в  5.0  % случаев.
Максимальное значение -  89.0
Минимальное значение -  3.3
Размах значений:  85.7
СКО -  27.475009470785064
Дисперсия -  754.8761454197289
Q1 -  6.5 ; Q3 -  57.0 ; IQR:  50.5
Кол-во выбросов из основного скопления данных по белку составило -  33 , из которых по причине того, что данные не были указаны -  33
По анализам белка ситуация не совсем стандартная. половина показателей по белку ниже или равна верхнему пределу нормы, а другая половина сильно завышена. И поэтому среднее значение по показателю белка сильно отличается и от медианы и от моды. В данном случае необходимо или не учитывать 33 строки с незанесенными данными, или исследовать более подробно зависимости показателя белка от других параметров и только после этого проставлять какое либо значение.
Кол-во актуальных выбросов из основного скопления данных по белку составило: 0
Значение медианы, и значение по первому квантилю говорят о том, что около у 1/2 лошадей кол-во белка было в пределах номры (от 6 до 7.5). И примерно у второй половины лошадей кол-во белка сильно завышено, и именно поэтому случаи с превышением белка в 10 раз выше верхнего предела нормы не попали в выбросы.
Выбросы без неуказанных значений:

,surg,age,Hosp_Num,rectal_temp,pulse,respiratory_rate,temp_of_extrem,perip_pulse,mucous_membranes,cap_ref_time,...,pack_cell_vol,total_protein,abdom_appearance,abdom_total_protein,outcome,surgical_lesion,25,26,27,cp_data
5,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,0.0,NaN,NaN,1.0,2,0,0,0,2
17,2.0,1,526639,37.5,48.0,24.0,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,1.0,2,0,0,0,2
25,2.0,1,529518,37.8,60.0,42.0,NaN,NaN,NaN,1.0,...,NaN,0.0,NaN,NaN,1.0,2,0,0,0,2
28,1.0,1,5279442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,2.0,2,4300,0,0,2
39,1.0,9,5277409,39.2,146.0,96.0,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,2.0,1,2113,0,0,2

In [377]:
print('Статистика по показателю вздутия живота: ')
print('--------------------------------------------------------------------------------------')
print('Данный показатель помечен в документации как Важный. Поэтому статистика по нему необходима.')
print('Возможные оценочные значения: 1 = вздутия нет; 2 = незначительное; 3 = умеренное; 4 = сильное')
print('Не у всех строк заполнено значение и часть строк несет значение NaN.')
print('Для корректности подсчета статистики заменю все значения NaN на 0 с учетом того, что это качественный показатель и он имеет значения в виде целых числе от 1 до 4.')
df['abdom_distension'].fillna(0, inplace = True)
print()
print('Итого данные по показателю: ')
print(df.groupby('abdom_distension').count()['Hosp_Num'])

print('Медиана по показателю вздутия живота - ', df.abdom_distension.median())
print('Мода по показателю вздутия живота - ', df.abdom_distension.mode()[0], '. Она наблюдалась в ', round(len(df.abdom_distension[df.abdom_distension == df.abdom_distension.mode()[0]])/len(df.abdom_distension)*100, 2), ' % случаев.')
q1 = df.abdom_distension.quantile(0.25)
q3 = df.abdom_distension.quantile(0.75)
print('Q1 - ', q1, '; Q3 - ', q3)
print('Не было занесено данных по ', len(df[df['abdom_distension'] == 0]), 'случаям болезни, что составляет', round(len(df[df['abdom_distension'] == 0])*100/len(df), 2), '%')
print('Вздутие не было обнаружено или было обнаружено незначительно по ', len(df[df['abdom_distension'] == 1]) + len(df[df['abdom_distension'] == 2]), 'случаям болезни, что составляет', round((len(df[df['abdom_distension'] == 1]) + len(df[df['abdom_distension'] == 2]))*100/len(df), 2), '%')
print('Было обнаружено умеренное вздутие по ', len(df[df['abdom_distension'] == 3]), 'случаям болезни, что составляет', round(len(df[df['abdom_distension'] == 3])*100/len(df), 2), '%')
print('Было обнаружено сильное вздутие по ', len(df[df['abdom_distension'] == 4]), 'случаям болезни, что составляет', round(len(df[df['abdom_distension'] == 4])*100/len(df), 2), '%')
print('В целом вздутие в той или иной степени силы наблюдалось по ', len(df[df['abdom_distension'] > 1]), 'случаям болезни, что составляет', round(len(df[df['abdom_distension'] > 1])*100/len(df), 2), '%')

Статистика по показателю вздутия живота:
--------------------------------------------------------------------------------------
Данный показатель помечен в документации как Важный. Поэтому статистика по нему необходима.
Возможные оценочные значения: 1 = вздутия нет; 2 = незначительное; 3 = умеренное; 4 = сильное
Не у всех строк заполнено значение и часть строк несет значение NaN.
Для корректности подсчета статистики заменю все значения NaN на 0 с учетом того, что это качественный показатель и он имеет значения в виде целых числе от 1 до 4.

Итого данные по показателю:
abdom_distension
0.0    56
1.0    76
2.0    65
3.0    65
4.0    38
Name: Hosp_Num, dtype: int64
Медиана по показателю вздутия живота -  2.0
Мода по показателю вздутия живота -  1.0 . Она наблюдалась в  25.33  % случаев.
Q1 -  1.0 ; Q3 -  3.0
Не было занесено данных по  56 случаям болезни, что составляет 18.67 %
Вздутие не было обнаружено или было обнаружено незначительно по  141 случаям болезни, что составляет 47.0 %
Было обнаружено умеренное вздутие по  65 случаям болезни, что составляет 21.67 %
Было обнаружено сильное вздутие по  38 случаям болезни, что составляет 12.67 %
В целом вздутие в той или иной степени силы наблюдалось по  168 случаям болезни, что составляет 56.0 %

In [398]:
df['rectal_temp'].fillna(df.rectal_temp.median(), inplace = True)
df['pulse'].fillna(round(df.pulse.mean()), inplace = True)
df['pack_cell_vol'].fillna(df.pack_cell_vol.median(), inplace = True)
df_end = df[['surg', 'age', 'Hosp_Num', 'rectal_temp', 'pulse', 'pack_cell_vol', 'surgical_lesion', 'outcome']]
df_end.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   surg             300 non-null    float64
 1   age              300 non-null    int64
 2   Hosp_Num         300 non-null    int64
 3   rectal_temp      300 non-null    float64
 4   pulse            300 non-null    float64
 5   pack_cell_vol    300 non-null    float64
 6   surgical_lesion  300 non-null    int64
 7   outcome          300 non-null    float64
dtypes: float64(5), int64(3)
memory usage: 18.9 KB

In [399]:
df_end

,surg,age,Hosp_Num,rectal_temp,pulse,pack_cell_vol,surgical_lesion,outcome
0,2.0,1,530101,38.5,66.0,45.0,2,2.0
1,1.0,1,534817,39.2,88.0,50.0,2,3.0
2,2.0,1,530334,38.3,40.0,33.0,2,1.0
3,1.0,9,5290409,39.1,164.0,48.0,1,2.0
4,2.0,1,530255,37.3,104.0,74.0,2,2.0
...,...,...,...,...,...,...,...,...
295,1.0,1,533886,38.2,120.0,55.0,2,3.0
296,2.0,1,527702,37.2,72.0,44.0,1,3.0
297,1.0,1,529386,37.5,72.0,60.0,1,2.0
298,1.0,1,530612,36.5,100.0,50.0,1,1.0
299,1.0,1,534618,37.2,40.0,36.0,2,3.0